[app]
name = "restful-api-demo"
host = "127.0.0.1"
port = "8080"
key  = "this is your app key"

[mysql]
host = "127.0.0.1"
port = "3306"
username = "root"
password = "123456789"
database = "cmdb"

[log]
level = "debug"
dir = "logs"
format = "text"
to = "stdout"